build:
  project_setup:
    override: true

  environment:
    variables:
      XDEBUG_MODE: coverage

  tests:
    after:
        - vendor/bin/phpcs --standard=phpcs.xml.dist src
        - php-scrutinizer-run --enable-security-analysis
    override:
      - command: vendor/bin/phpunit
        coverage:
          file: build/phpunit/coverage/coverage.clover.xml
          format: clover

  nodes:
    php73:
      environment:
        php: 7.3

    php74:
      environment:
        php: 7.4

    # php80:
    #   environment:
    #     php: 8.0


filter:
  excluded_paths:
    - tests/
  dependency_paths:
    - vendor/
    - assets/node_modules/


checks:
  php: true
