build:
  environment:
    variables:
      XDEBUG_MODE: coverage
  dependencies:
    override:
      - composer install --no-interaction --no-scripts
  tests:
    override:
      - command: vendor/bin/phpunit
        coverage:
          file: build/phpunit/coverage/coverage.clover.xml
          format: clover

  nodes:
    php-analysis:
      tests:
        override:
          - vendor/bin/phpcs
          - php-scrutinizer-run --enable-security-analysis
    php-7.3:
      environment:
        php: 7.3
    php-7.4:
      environment:
        php: 7.4
    php-8.0:
      environment:
        php: 8.0

filter:
  excluded_paths:
    - tests/
    - assets/tests/
  dependency_paths:
    - vendor/
    - wordpress/
    - assets/node_modules/

checks:
  php: true
