build:
  project_setup:
    override: true
  tests:
    override:
          - php-scrutinizer-run --enable-security-analysis
  nodes:
    php73:
      environment:
        php: 7.3

    php74:
      environment:
        php: 7.4

    php80:
      environment:
        php: 8.0


filter:
  excluded_paths:
    - tests/
  dependency_paths:
    - vendor/
    - assets/node_modules


tools:
  external_code_coverage:
    timeout: 600
    runs: 3
