services:
  app:
    build:
      target: app-interactive
      args:
        LANG: "${LANG}"
        TZ:
        UNMINIMIZE: yes
        USER: "${USER}"
        GIT_USER:
        GIT_EMAIL:
        GIT_DEFAULT_BRANCH: "master"
        GIT_INSTALL_GCM: yes
    ports:
      - "${BROWSERSYNC_PORT:-3000}:${BROWSERSYNC_PORT:-3000}"
      - "${BROWSERSYNC_UI_PORT:-3001}:${BROWSERSYNC_UI_PORT:-3001}"
    environment:
      TERM: "${TERM}"
      ZSH_THEME: "powerlevel10k/powerlevel10k"
    volumes:
      # Source
      - ".:/var/www/html"
      # Credentials
      - "~/.config/composer/auth.json:/home/leonidas/.config/composer/auth.json"
      # Vscode server
      - "vscode:/home/leonidas/.vscode-server"

  webserver:
    networks:
      - nginx-proxy
    environment:
      TERM: "${TERM}"
      VIRTUAL_HOST: "${SERVER_NAME}"
    volumes:
      - ".:/var/www/html:ro"

  database:
    ports:
      - "${DB_FORWARD_PORT:-3306}:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TERM: "${TERM}"

  cache:
    ports:
      - "${CACHE_FORWARD_PORT:-6379}:6379"
    environment:
      TERM: "${TERM}"

  selenium:
    environment:
      TERM: "${TERM}"

networks:
  nginx-proxy:
    external: true

volumes:
  vscode:
    driver: local
