name: leonidas

services:
  app:
    build:
      target: app-workspace
      args:
        UNMINIMIZE: yes
        GIT_USER:
        GIT_EMAIL:
        GIT_DEFAULT_BRANCH: "master"
        GIT_INSTALL_GCM: yes
        LANG: "${LANG}"
        TZ: "${TZ}"
    healthcheck:
      interval: 2s
      timeout: 2s
      start_period: 10s
      retries: 5
    ports:
      - "${BROWSERSYNC_PORT:-3000}:${BROWSERSYNC_PORT:-3000}"
      - "${BROWSERSYNC_UI_PORT:-3001}:${BROWSERSYNC_UI_PORT:-3001}"
    environment:
      ZSH_THEME: "powerlevel10k/powerlevel10k"
      TERM: "${TERM}"
    volumes:
      # Source
      - ".:/var/www/html"
      # Credentials
      - "~/.config/composer/auth.json:/home/leonidas/.config/composer/auth.json"
      # Vscode server
      - "vscode:/home/leonidas/.vscode-server"

  webserver:
    build:
      target: webserver-local
    networks:
      - nginx-proxy
    hostname: "${SERVER_NAME}"
    environment:
      VIRTUAL_HOST: "${SERVER_NAME}"
      LANG: "${LANG}"
      TZ: "${TZ}"
      TERM: "${TERM}"
    volumes:
      - ".:/var/www/html:ro"

  database:
    ports:
      - "${DB_FORWARD_PORT:-3306}:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TERM: "${TERM}"

  cache:
    ports:
      - "${CACHE_FORWARD_PORT:-6379}:6379"
    environment:
      TERM: "${TERM}"

  browser:
    environment:
      TERM: "${TERM}"

networks:
  nginx-proxy:
    external: true

volumes:
  vscode:
    driver: local
